# Generated by Django 5.1.3 on 2024-12-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_alter_models_model_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='updated_at',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
